version: 2.1
parameters:
  test_variable:
    type: string
    default: "test_variable"
  testomatio:
    type: string
    default: "testomatio"
  testomatio_url:
    type: string
    default: "testomatio_url"
  run:
    type: string
    default: "run"
  block:
    type: string
    default: "block"

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1
    steps:
      - run: echo 'built'
      - run: echo << pipeline.parameters.test_variable >>

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
